// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: atefleet.proto

package atefleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchActorRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ActorTemplateNamespace string                 `protobuf:"bytes,1,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,2,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	ActorId                string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // required for MVP (DNS-1123 label)
	Role                   string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Owner                  string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Group                  string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	TtlSeconds             int64                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = no expiry
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DispatchActorRequest) Reset() {
	*x = DispatchActorRequest{}
	mi := &file_atefleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchActorRequest) ProtoMessage() {}

func (x *DispatchActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchActorRequest.ProtoReflect.Descriptor instead.
func (*DispatchActorRequest) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchActorRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *DispatchActorRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *DispatchActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *DispatchActorRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DispatchActorRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DispatchActorRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DispatchActorRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type FleetActor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // <actor_id>.actors.resources.substrate.ate.dev
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // ateapi Actor.Status name, e.g. "STATUS_RUNNING"
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	ExpiryUnix    int64                  `protobuf:"varint,7,opt,name=expiry_unix,json=expiryUnix,proto3" json:"expiry_unix,omitempty"` // 0 = none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetActor) Reset() {
	*x = FleetActor{}
	mi := &file_atefleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetActor) ProtoMessage() {}

func (x *FleetActor) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetActor.ProtoReflect.Descriptor instead.
func (*FleetActor) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{1}
}

func (x *FleetActor) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *FleetActor) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FleetActor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FleetActor) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *FleetActor) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FleetActor) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FleetActor) GetExpiryUnix() int64 {
	if x != nil {
		return x.ExpiryUnix
	}
	return 0
}

type DispatchActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *FleetActor            `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchActorResponse) Reset() {
	*x = DispatchActorResponse{}
	mi := &file_atefleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchActorResponse) ProtoMessage() {}

func (x *DispatchActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchActorResponse.ProtoReflect.Descriptor instead.
func (*DispatchActorResponse) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchActorResponse) GetActor() *FleetActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ListFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetRequest) Reset() {
	*x = ListFleetRequest{}
	mi := &file_atefleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetRequest) ProtoMessage() {}

func (x *ListFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetRequest.ProtoReflect.Descriptor instead.
func (*ListFleetRequest) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{3}
}

func (x *ListFleetRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListFleetRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListFleetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListFleetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*FleetActor          `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetResponse) Reset() {
	*x = ListFleetResponse{}
	mi := &file_atefleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetResponse) ProtoMessage() {}

func (x *ListFleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetResponse.ProtoReflect.Descriptor instead.
func (*ListFleetResponse) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{4}
}

func (x *ListFleetResponse) GetActors() []*FleetActor {
	if x != nil {
		return x.Actors
	}
	return nil
}

type GetFleetActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFleetActorRequest) Reset() {
	*x = GetFleetActorRequest{}
	mi := &file_atefleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetActorRequest) ProtoMessage() {}

func (x *GetFleetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetActorRequest.ProtoReflect.Descriptor instead.
func (*GetFleetActorRequest) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{5}
}

func (x *GetFleetActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type GetFleetActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *FleetActor            `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFleetActorResponse) Reset() {
	*x = GetFleetActorResponse{}
	mi := &file_atefleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetActorResponse) ProtoMessage() {}

func (x *GetFleetActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetActorResponse.ProtoReflect.Descriptor instead.
func (*GetFleetActorResponse) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{6}
}

func (x *GetFleetActorResponse) GetActor() *FleetActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type TerminateActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateActorRequest) Reset() {
	*x = TerminateActorRequest{}
	mi := &file_atefleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateActorRequest) ProtoMessage() {}

func (x *TerminateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateActorRequest.ProtoReflect.Descriptor instead.
func (*TerminateActorRequest) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{7}
}

func (x *TerminateActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type TerminateActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateActorResponse) Reset() {
	*x = TerminateActorResponse{}
	mi := &file_atefleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateActorResponse) ProtoMessage() {}

func (x *TerminateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atefleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateActorResponse.ProtoReflect.Descriptor instead.
func (*TerminateActorResponse) Descriptor() ([]byte, []int) {
	return file_atefleet_proto_rawDescGZIP(), []int{8}
}

var File_atefleet_proto protoreflect.FileDescriptor

const file_atefleet_proto_rawDesc = "" +
	"\n" +
	"\x0eatefleet.proto\x12\batefleet\"\xfc\x01\n" +
	"\x14DispatchActorRequest\x128\n" +
	"\x18actor_template_namespace\x18\x01 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x02 \x01(\tR\x11actorTemplateName\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x03R\n" +
	"ttlSeconds\"\xba\x01\n" +
	"\n" +
	"FleetActor\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x1f\n" +
	"\vexpiry_unix\x18\a \x01(\x03R\n" +
	"expiryUnix\"C\n" +
	"\x15DispatchActorResponse\x12*\n" +
	"\x05actor\x18\x01 \x01(\v2\x14.atefleet.FleetActorR\x05actor\"R\n" +
	"\x10ListFleetRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"A\n" +
	"\x11ListFleetResponse\x12,\n" +
	"\x06actors\x18\x01 \x03(\v2\x14.atefleet.FleetActorR\x06actors\"1\n" +
	"\x14GetFleetActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"C\n" +
	"\x15GetFleetActorResponse\x12*\n" +
	"\x05actor\x18\x01 \x01(\v2\x14.atefleet.FleetActorR\x05actor\"2\n" +
	"\x15TerminateActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"\x18\n" +
	"\x16TerminateActorResponse2\xd5\x02\n" +
	"\fFleetManager\x12R\n" +
	"\rDispatchActor\x12\x1e.atefleet.DispatchActorRequest\x1a\x1f.atefleet.DispatchActorResponse\"\x00\x12F\n" +
	"\tListFleet\x12\x1a.atefleet.ListFleetRequest\x1a\x1b.atefleet.ListFleetResponse\"\x00\x12R\n" +
	"\rGetFleetActor\x12\x1e.atefleet.GetFleetActorRequest\x1a\x1f.atefleet.GetFleetActorResponse\"\x00\x12U\n" +
	"\x0eTerminateActor\x12\x1f.atefleet.TerminateActorRequest\x1a .atefleet.TerminateActorResponse\"\x00B@Z>github.com/agent-substrate/substrate/internal/proto/atefleetpbb\x06proto3"

var (
	file_atefleet_proto_rawDescOnce sync.Once
	file_atefleet_proto_rawDescData []byte
)

func file_atefleet_proto_rawDescGZIP() []byte {
	file_atefleet_proto_rawDescOnce.Do(func() {
		file_atefleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atefleet_proto_rawDesc), len(file_atefleet_proto_rawDesc)))
	})
	return file_atefleet_proto_rawDescData
}

var file_atefleet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_atefleet_proto_goTypes = []any{
	(*DispatchActorRequest)(nil),   // 0: atefleet.DispatchActorRequest
	(*FleetActor)(nil),             // 1: atefleet.FleetActor
	(*DispatchActorResponse)(nil),  // 2: atefleet.DispatchActorResponse
	(*ListFleetRequest)(nil),       // 3: atefleet.ListFleetRequest
	(*ListFleetResponse)(nil),      // 4: atefleet.ListFleetResponse
	(*GetFleetActorRequest)(nil),   // 5: atefleet.GetFleetActorRequest
	(*GetFleetActorResponse)(nil),  // 6: atefleet.GetFleetActorResponse
	(*TerminateActorRequest)(nil),  // 7: atefleet.TerminateActorRequest
	(*TerminateActorResponse)(nil), // 8: atefleet.TerminateActorResponse
}
var file_atefleet_proto_depIdxs = []int32{
	1, // 0: atefleet.DispatchActorResponse.actor:type_name -> atefleet.FleetActor
	1, // 1: atefleet.ListFleetResponse.actors:type_name -> atefleet.FleetActor
	1, // 2: atefleet.GetFleetActorResponse.actor:type_name -> atefleet.FleetActor
	0, // 3: atefleet.FleetManager.DispatchActor:input_type -> atefleet.DispatchActorRequest
	3, // 4: atefleet.FleetManager.ListFleet:input_type -> atefleet.ListFleetRequest
	5, // 5: atefleet.FleetManager.GetFleetActor:input_type -> atefleet.GetFleetActorRequest
	7, // 6: atefleet.FleetManager.TerminateActor:input_type -> atefleet.TerminateActorRequest
	2, // 7: atefleet.FleetManager.DispatchActor:output_type -> atefleet.DispatchActorResponse
	4, // 8: atefleet.FleetManager.ListFleet:output_type -> atefleet.ListFleetResponse
	6, // 9: atefleet.FleetManager.GetFleetActor:output_type -> atefleet.GetFleetActorResponse
	8, // 10: atefleet.FleetManager.TerminateActor:output_type -> atefleet.TerminateActorResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_atefleet_proto_init() }
func file_atefleet_proto_init() {
	if File_atefleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atefleet_proto_rawDesc), len(file_atefleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atefleet_proto_goTypes,
		DependencyIndexes: file_atefleet_proto_depIdxs,
		MessageInfos:      file_atefleet_proto_msgTypes,
	}.Build()
	File_atefleet_proto = out.File
	file_atefleet_proto_goTypes = nil
	file_atefleet_proto_depIdxs = nil
}
