// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: atefleet.proto

package atefleetpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetManager_DispatchActor_FullMethodName  = "/atefleet.FleetManager/DispatchActor"
	FleetManager_ListFleet_FullMethodName      = "/atefleet.FleetManager/ListFleet"
	FleetManager_GetFleetActor_FullMethodName  = "/atefleet.FleetManager/GetFleetActor"
	FleetManager_TerminateActor_FullMethodName = "/atefleet.FleetManager/TerminateActor"
)

// FleetManagerClient is the client API for FleetManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetManagerClient interface {
	DispatchActor(ctx context.Context, in *DispatchActorRequest, opts ...grpc.CallOption) (*DispatchActorResponse, error)
	ListFleet(ctx context.Context, in *ListFleetRequest, opts ...grpc.CallOption) (*ListFleetResponse, error)
	GetFleetActor(ctx context.Context, in *GetFleetActorRequest, opts ...grpc.CallOption) (*GetFleetActorResponse, error)
	TerminateActor(ctx context.Context, in *TerminateActorRequest, opts ...grpc.CallOption) (*TerminateActorResponse, error)
}

type fleetManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetManagerClient(cc grpc.ClientConnInterface) FleetManagerClient {
	return &fleetManagerClient{cc}
}

func (c *fleetManagerClient) DispatchActor(ctx context.Context, in *DispatchActorRequest, opts ...grpc.CallOption) (*DispatchActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchActorResponse)
	err := c.cc.Invoke(ctx, FleetManager_DispatchActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) ListFleet(ctx context.Context, in *ListFleetRequest, opts ...grpc.CallOption) (*ListFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFleetResponse)
	err := c.cc.Invoke(ctx, FleetManager_ListFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) GetFleetActor(ctx context.Context, in *GetFleetActorRequest, opts ...grpc.CallOption) (*GetFleetActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFleetActorResponse)
	err := c.cc.Invoke(ctx, FleetManager_GetFleetActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) TerminateActor(ctx context.Context, in *TerminateActorRequest, opts ...grpc.CallOption) (*TerminateActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateActorResponse)
	err := c.cc.Invoke(ctx, FleetManager_TerminateActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetManagerServer is the server API for FleetManager service.
// All implementations must embed UnimplementedFleetManagerServer
// for forward compatibility.
type FleetManagerServer interface {
	DispatchActor(context.Context, *DispatchActorRequest) (*DispatchActorResponse, error)
	ListFleet(context.Context, *ListFleetRequest) (*ListFleetResponse, error)
	GetFleetActor(context.Context, *GetFleetActorRequest) (*GetFleetActorResponse, error)
	TerminateActor(context.Context, *TerminateActorRequest) (*TerminateActorResponse, error)
	mustEmbedUnimplementedFleetManagerServer()
}

// UnimplementedFleetManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetManagerServer struct{}

func (UnimplementedFleetManagerServer) DispatchActor(context.Context, *DispatchActorRequest) (*DispatchActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchActor not implemented")
}
func (UnimplementedFleetManagerServer) ListFleet(context.Context, *ListFleetRequest) (*ListFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFleet not implemented")
}
func (UnimplementedFleetManagerServer) GetFleetActor(context.Context, *GetFleetActorRequest) (*GetFleetActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFleetActor not implemented")
}
func (UnimplementedFleetManagerServer) TerminateActor(context.Context, *TerminateActorRequest) (*TerminateActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateActor not implemented")
}
func (UnimplementedFleetManagerServer) mustEmbedUnimplementedFleetManagerServer() {}
func (UnimplementedFleetManagerServer) testEmbeddedByValue()                      {}

// UnsafeFleetManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetManagerServer will
// result in compilation errors.
type UnsafeFleetManagerServer interface {
	mustEmbedUnimplementedFleetManagerServer()
}

func RegisterFleetManagerServer(s grpc.ServiceRegistrar, srv FleetManagerServer) {
	// If the following call panics, it indicates UnimplementedFleetManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetManager_ServiceDesc, srv)
}

func _FleetManager_DispatchActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).DispatchActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_DispatchActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).DispatchActor(ctx, req.(*DispatchActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_ListFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).ListFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_ListFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).ListFleet(ctx, req.(*ListFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_GetFleetActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFleetActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).GetFleetActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_GetFleetActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).GetFleetActor(ctx, req.(*GetFleetActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_TerminateActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).TerminateActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_TerminateActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).TerminateActor(ctx, req.(*TerminateActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetManager_ServiceDesc is the grpc.ServiceDesc for FleetManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atefleet.FleetManager",
	HandlerType: (*FleetManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchActor",
			Handler:    _FleetManager_DispatchActor_Handler,
		},
		{
			MethodName: "ListFleet",
			Handler:    _FleetManager_ListFleet_Handler,
		},
		{
			MethodName: "GetFleetActor",
			Handler:    _FleetManager_GetFleetActor_Handler,
		},
		{
			MethodName: "TerminateActor",
			Handler:    _FleetManager_TerminateActor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atefleet.proto",
}
